language: go

go:
  - 1.12.x

before_install:
  - GO111MODULE=on go get -v golang.org/x/lint/golint
  - GO111MODULE=on go get github.com/mattn/goveralls

script:
  - >
    if [ -n "$(gofmt -l .)" ]; then
      echo "Go code is not formatted:"
      gofmt -d .
      exit 1
    fi
  - >
    GO111MODULE=on go vet ./...;
    retval=$?;
    if [ $retval -ne 0 ]; then
        echo "There are some go vet errors.";
        exit 1
    fi
  - >
    if [ -n "$(golint ./...)" ]; then
      echo "There are some lint errors:"
      golint ./...
      exit 1
    fi
  - GO111MODULE=on go test -v -race ./...
  - >
    go_version=$(go version);
    if [ ${go_version:13:4} = "1.12" ]; then
      go get -u golang.org/x/tools/cmd/goimports;
      goimports -d -e ./ | grep '.*' && { echo; echo "Aborting due to non-empty goimports output."; exit 1; } || :;
    fi

  - $GOPATH/bin/goveralls -service=travis-ci

