language: go

go:
  - 1.12.x

before_install:
  - GO111MODULE=on go get -v golang.org/x/lint/golint

install:
  - GO111MODULE=on go get github.com/modocache/gover
  - GO111MODULE=on go get github.com/mattn/goveralls
  - GO111MODULE=on go get github.com/GeertJohan/fgt

script:
  - >
    if [ -n "$(gofmt -l .)" ]; then
      echo "Go code is not formatted:"
      gofmt -d .
      exit 1
    fi
  - GO111MODULE=on go vet ./...
  - retval=$?
  - >
    echo $retval;
    if [ $? -eq 0 ]; then
      echo "Go code is not vet:"
      GO111MODULE=on go vet ./...
      exit 1
    else
      echo $retval
    fi
  - >
    if [ -n "$(golint ./...)" ]; then
      echo "There are some lint errors:"
      golint ./...
      exit 1
    fi
  - GO111MODULE=on go test -v -race ./...
  - >
    go_version=$(go version);
    if [ ${go_version:13:4} = "1.12" ]; then
      go get -u golang.org/x/tools/cmd/goimports;
      goimports -d -e ./ | grep '.*' && { echo; echo "Aborting due to non-empty goimports output."; exit 1; } || :;
    fi

  - gover
  - goveralls -coverprofile gover.coverprofile -service travis-ci

