language: go

go:
  - 1.11.x
  - 1.12.x

before_install:
  - GO111MODULE=on go get -v golang.org/x/lint/golint


script:
  - GO111MODULE=on go get -d -t ./...
  - GO111MODULE=on go fmt ./...
  - GO111MODULE=on go vet ./...
  - GO111MODULE=on golint ./...
  - GO111MODULE=on go test ./...
  - >
    go_version=$(go version);
    if [ ${go_version:13:4} = "1.12" ]; then
      go get -u golang.org/x/tools/cmd/goimports;
      goimports -d -e ./ | grep '.*' && { echo; echo "Aborting due to non-empty goimports output."; exit 1; } || :;
    fi